version: "3"

services:
 influxdb:
      image: influxdb:latest
      container_name: influxdb
      ports:
        - "8086:8086"
      user: ${CURRENT_UID}
      networks:
      - infraestructure
      volumes:
        - ${DATA_DIR}/influxdb:/var/lib/influxdb
      environment:
        INFLUXDB_USER: sphere_admin
        INFLUXDB_USER_PASSWORD: sphere
      restart: unless-stopped
 grafana:
      image: grafana/grafana:latest
      container_name: grafana
      depends_on:
        - influxdb
      ports:
        - "3000:3000"
      user: ${CURRENT_UID}
      networks:
      - infraestructure
      volumes:
        - ${DATA_DIR}/grafana:/var/lib/grafana
      environment:
        GF_SECURITY_ADMIN_USER: sphere
        GF_SECURITY_ADMIN_PASSWORD: sphere
      restart: unless-stopped


networks:
  infraestructure:
    driver: bridge
